# Generated by Django 4.0.1 on 2022-01-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr', models.CharField(blank=True, max_length=200, null=True)),
                ('eng', models.CharField(max_length=200)),
                ('tnm', models.CharField(max_length=800)),
                ('dfn', models.CharField(max_length=800)),
            ],
        ),
    ]
