# Generated by Django 4.0.1 on 2022-01-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='dfn',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='terms',
            name='eng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='terms',
            name='tnm',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
