# Generated by Django 4.0.1 on 2022-02-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0002_alter_terms_dfn_alter_terms_eng_alter_terms_tnm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abr',
            fields=[
                ('abr', models.CharField(blank=True, max_length=200, null=True)),
                ('meaning', models.TextField()),
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='terms',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='terms',
            name='dfn',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='terms',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='terms',
            name='tnm',
            field=models.TextField(default=''),
        ),
    ]
