# Generated by Django 4.0.1 on 2022-02-14 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0003_abr_alter_terms_options_alter_terms_dfn_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Terms',
            new_name='Term',
        ),
    ]
