# Generated by Django 4.0.1 on 2022-02-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.TextField()),
                ('from_email', models.EmailField(max_length=254)),
                ('word', models.CharField(max_length=255)),
                ('problem_def', models.TextField()),
                ('proposed_solution', models.TextField()),
            ],
        ),
    ]
