# Generated by Django 4.0.1 on 2022-02-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='from_email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='from_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='problem_def',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='proposed_solution',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='word',
        ),
        migrations.AddField(
            model_name='contact',
            name='degisim',
            field=models.CharField(default='', max_length=255, verbose_name='Değiştirilecek/Eklenecek Terim/Kısaltma'),
        ),
        migrations.AddField(
            model_name='contact',
            name='eposta',
            field=models.EmailField(default='', max_length=254, verbose_name='E-posta Adresi'),
        ),
        migrations.AddField(
            model_name='contact',
            name='isim',
            field=models.CharField(default='', max_length=255, verbose_name='İsim'),
        ),
        migrations.AddField(
            model_name='contact',
            name='oneri',
            field=models.CharField(default='', max_length=600, verbose_name='Önerilen Değişiklik/Ekleme'),
        ),
        migrations.AddField(
            model_name='contact',
            name='problem',
            field=models.CharField(default='', max_length=600, verbose_name='Problem Tanımı(Opsiyonel)'),
        ),
    ]
