# Generated by Django 4.0.1 on 2022-02-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contact_from_email_remove_contact_from_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='oneri',
            field=models.CharField(blank=True, default='', max_length=600, verbose_name='Önerilen Değişiklik/Ekleme'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='problem',
            field=models.CharField(blank=True, default='', max_length=600, verbose_name='Problem Tanımı(Opsiyonel)'),
        ),
    ]
