# Generated by Django 4.0.1 on 2022-02-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contact_oneri_alter_contact_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='degisim',
            field=models.CharField(default='', max_length=255, verbose_name='Değiştirilecek/Eklenecek Terim/Kısaltma*'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='eposta',
            field=models.EmailField(default='', max_length=254, verbose_name='E-posta Adresi*'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='isim',
            field=models.CharField(default='', max_length=255, verbose_name='İsim*'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='oneri',
            field=models.CharField(blank=True, default='', max_length=600, verbose_name='Önerilen Değişiklik/Ekleme(Opsiyonel)'),
        ),
    ]
